site_name: 5 Data Glow UP
theme:
  name: material
  palette:
    primary: deep blue
  language: pt
nav:
  - Home: index.md
  - Report Pandas Profiling: reports/pandas_profiling_report.html
  - Report SweetViz: reports/sweetviz_report.html
  - Utils: utils.md

repo_name: "lvgalvao/5DataGlowUp_lvgalvaofilho"
repo_url: "https://github.com/lvgalvao/5DataGlowUp_lvgalvaofilho"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - search
  - mkdocstrings:
      default_handler: python
